name: Ruff Linter and Formatter

jobs:
  lint-and-format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Knowledge Base
        run: |
          cd apps/knowledge_base
          echo "Knowledge Base: Installing dependencies..."
          uv sync --all-extras --dev
          echo "Knowledge Base: Ruff check..."
          uv run ruff check

      - name: CLI Sage
        run: |
          cd apps/cli-sage
          echo "CLI Sage: Installing dependencies..."
          uv sync --all-extras --dev
          echo "CLI Sage: Ruff check..."
          uv run ruff check